Parameters:
# New Bucket name
    MyBucketName:
      Description: Existing Bucket name
      Type: String
      Default: newbucket1988
Resources:
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub "${MyBucketName}"
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: users.html
          ErrorDocument: error.html
    WebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref 'WebsiteBucket'
        PolicyDocument:
          Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]